In the following cells, we import the Python package `numpy`, which gives us the methods for performing matrix operations, record the $E_8$ matrix in the variable `E8`, record the 120 positive roots of the $E_8$ lattice in the list `Posroots`, record the 2160 vectors in $E_8$ of norm 4 in the list `Norm4`, and record the possible $E_8$-projections of a loaded basis element in the list `loaded_stems`.

In [2]:
import numpy as np

E8 = np.array([[2,-1,-1,0,-1,0,0,0],
             [-1,2,0,0,0,0,0,0],
             [-1,0,2,-1,0,0,0,0],
             [0,0,-1,2,0,0,0,0],
             [-1,0,0,0,2,-1,0,0],
             [0,0,0,0,-1,2,-1,0],
             [0,0,0,0,0,-1,2,-1],
             [0,0,0,0,0,0,-1,2]],)

posroots = []
for a in range(0,7,1):
    for b in range(0,4,1):
        for c in range(0,5,1):
            for d in range(0,3,1):
                for e in range(0,6,1):
                    for f in range(0,5,1):
                        for g in range(0,4,1):
                            for h in range(0,3,1):
                                if np.dot(np.dot(np.array([a,b,c,d,e,f,g,h]),E8), np.array([[a],[b],[c],[d],[e],[f],[g],[h]])) ==2:
                                    posroots.append((a,b,c,d,e,f,g,h))
                                    
norm4 = []
for a in posroots:
    for b in posroots:
        if np.dot(np.dot(np.array(a), E8),np.transpose([np.array(b)])) == 0:
            norm4.append(tuple(a[i]+b[i] for i in range(len(a))))
            norm4.append(tuple(a[i]-b[i] for i in range(len(b))))
            norm4.append(tuple(-a[i]-b[i] for i in range(len(b))))
            norm4 = list(set(sorted(norm4)))
norm4 = sorted(norm4)

In [3]:
Posroots = [np.array(posroot) for posroot in posroots]
Norm4 = [np.array(normy) for normy in norm4]
loaded_stems = [(0, 1, -1, 0, 0, 0, 0, 0),
               (0, -1, 1, 0, 0, 0, 0, 0),
               (0, -1, 1, 1, 0, 0, 0, 0),
               (0, -1, 0, 1, 0, 0, 0, 0),
               (0, 1, 0, -1, 0, 0, 0, 0),
               (1, 1, 0, -1, 0, 0, 0, 0),
               (1, 1, 0, -1, 1, 0, 0, 0),
               (1, 1, 0, -1, 1, 1, 0, 0),
               (1, 1, 0, -1, 1, 1, 1, 0),
               (1, 1, 0, -1, 1, 1, 1, 1),
               (1, 0, 0, -1, 0, 0, 0, 0),
               (1, 0, 0, -1, 1, 0, 0, 0),
               (1, 0, 0, -1, 1, 1, 0, 0),
               (1, 0, 0, -1, 1, 1, 1, 0),
               (1, 0, 0, -1, 1, 1, 1, 1),
               (0, 0, 0, -1, 1, 0, 0, 0),
               (0, 0, 0, -1, 1, 1, 0, 0),
               (0, 0, 0, -1, 1, 1, 1, 0),
               (0, 0, 0, -1, 1, 1, 1, 1),
               (0, 0, 0, -1, 0, 1, 0, 0),
               (0, 0, 0, -1, 0, 1, 1, 0),
               (0, 0, 0, -1, 0, 1, 1, 1),
               (0, 0, 0, -1, 0, 0, 1, 0),
               (0, 0, 0, -1, 0, 0, 1, 1),
               (0, 0, 0, -1, 0, 0, 0, 1)]

In [4]:
Loaded = [np.array(stem) for stem in loaded_stems]

In the following cell, we have a script that, for each loaded stem `stem`, finds all positive roots `root` that pair to 0 with `root` + `stem`. We record the root `root` if, furthermore, `root[i]` = 0 for `i` the loaded index of `stem`, since otherwise we would have `root[i]` >0 and therefore the pairing of `root` with $\tau$ exceeds $|\sigma|_1$.

In [5]:
z2p0s = []
for stem in Loaded:
    i = list(stem).index(-1)
    working_list = []
    for root in Posroots:
        if (root + stem)@E8@(-root) == 0 and root[i] == 0:
            working_list.append(root)
    z2p0s.append(['These are for ' + str(stem) + ':', working_list])

We see in the following cell, that there are no such roots.

In [6]:
z2p0s

[['These are for [ 0  1 -1  0  0  0  0  0]:', []],
 ['These are for [ 0 -1  1  0  0  0  0  0]:', []],
 ['These are for [ 0 -1  1  1  0  0  0  0]:', []],
 ['These are for [ 0 -1  0  1  0  0  0  0]:', []],
 ['These are for [ 0  1  0 -1  0  0  0  0]:', []],
 ['These are for [ 1  1  0 -1  0  0  0  0]:', []],
 ['These are for [ 1  1  0 -1  1  0  0  0]:', []],
 ['These are for [ 1  1  0 -1  1  1  0  0]:', []],
 ['These are for [ 1  1  0 -1  1  1  1  0]:', []],
 ['These are for [ 1  1  0 -1  1  1  1  1]:', []],
 ['These are for [ 1  0  0 -1  0  0  0  0]:', []],
 ['These are for [ 1  0  0 -1  1  0  0  0]:', []],
 ['These are for [ 1  0  0 -1  1  1  0  0]:', []],
 ['These are for [ 1  0  0 -1  1  1  1  0]:', []],
 ['These are for [ 1  0  0 -1  1  1  1  1]:', []],
 ['These are for [ 0  0  0 -1  1  0  0  0]:', []],
 ['These are for [ 0  0  0 -1  1  1  0  0]:', []],
 ['These are for [ 0  0  0 -1  1  1  1  0]:', []],
 ['These are for [ 0  0  0 -1  1  1  1  1]:', []],
 ['These are for [ 0  0  0 -1  

We now turn our attention to finding all positive roots `root` that pair to 1 with `root` + `stem`, recording only those roots with `root[i]` = 0 for `i` the loaded index of `stem`.

In [12]:
z2p1s = []
for stem in Loaded:
    i = list(stem).index(-1)
    working_list = []
    for root in Posroots:
        if (root + stem)@E8@(-root) == -1 and root[i] == 0:
            working_list.append(root)
    z2p1s.append(['These are for ' + str(stem) + ':', working_list])

We see in the following cell that for each pair (`stem`, `root`), either 
    1) `root` $\cdot \tau = 0$, 
    2) `root` $\cdot \tau > |\sigma|_1 + 1$, or 
    3) (`root` + `stem`) $\cdot \tau > 0$.

In [13]:
z2p1s

[['These are for [ 0  1 -1  0  0  0  0  0]:', []],
 ['These are for [ 0 -1  1  0  0  0  0  0]:',
  [array([0, 0, 0, 1, 0, 0, 0, 0])]],
 ['These are for [ 0 -1  1  1  0  0  0  0]:', []],
 ['These are for [ 0 -1  0  1  0  0  0  0]:',
  [array([0, 0, 1, 0, 0, 0, 0, 0])]],
 ['These are for [ 0  1  0 -1  0  0  0  0]:',
  [array([1, 0, 0, 0, 0, 0, 0, 0]),
   array([1, 0, 0, 0, 1, 0, 0, 0]),
   array([1, 0, 0, 0, 1, 1, 0, 0]),
   array([1, 0, 0, 0, 1, 1, 1, 0]),
   array([1, 0, 0, 0, 1, 1, 1, 1])]],
 ['These are for [ 1  1  0 -1  0  0  0  0]:',
  [array([0, 0, 0, 0, 1, 0, 0, 0]),
   array([0, 0, 0, 0, 1, 1, 0, 0]),
   array([0, 0, 0, 0, 1, 1, 1, 0]),
   array([0, 0, 0, 0, 1, 1, 1, 1])]],
 ['These are for [ 1  1  0 -1  1  0  0  0]:',
  [array([0, 0, 0, 0, 0, 1, 0, 0]),
   array([0, 0, 0, 0, 0, 1, 1, 0]),
   array([0, 0, 0, 0, 0, 1, 1, 1])]],
 ['These are for [ 1  1  0 -1  1  1  0  0]:',
  [array([0, 0, 0, 0, 0, 0, 1, 0]), array([0, 0, 0, 0, 0, 0, 1, 1])]],
 ['These are for [ 1  1  0 -1  1  1  

In the following cell, we identify all vectors `norm4` of norm 4 which pair to 1 with `norm4 + stem`, recording only those which satisfy $0 \leq$ `norm4` $\cdot \tau \leq |\sigma|_1 + 1$ and `norm4[i]` + `stem[i]` $\leq -1$ for some $0\leq i \leq 7$.

In [18]:
z4p1s = []
for stem in Loaded:
    working_list = []
    for norm4 in Norm4:
        i = list(stem).index(-1)
        b = 0
        c = 0
        d = 0
        for a in norm4:
            if a >= 0:
                c+= (a >0)
                b += 1
        for j in range(8):
            if norm4[j] + stem[j] >= 0:
                d += 1
        if c > 0 and (norm4 + stem)@E8@(-norm4) == -1 and not(b == 8 and norm4[i] >= 1) and d < 8:
            working_list.append(norm4)
    z4p1s.append(['These are for ' + str(stem) + ':', working_list])

For all `norm4` identified by the script above, either (`norm4` + `stem`) $\cdot \tau <-|\sigma|_1 -1$, or $0 = ($ `norm4` + `stem` $)\cdot \tau$ and `abs`(`norm4` + `stem` ) = 2, or (`norm4` + `stem`) $\cdot \tau > 0$.

In [20]:
z4p1s

[['These are for [ 0  1 -1  0  0  0  0  0]:', []],
 ['These are for [ 0 -1  1  0  0  0  0  0]:',
  [array([ 0,  1, -1, -1,  0,  0,  0,  0])]],
 ['These are for [ 0 -1  1  1  0  0  0  0]:', []],
 ['These are for [ 0 -1  0  1  0  0  0  0]:',
  [array([ 0,  1, -1, -1,  0,  0,  0,  0])]],
 ['These are for [ 0  1  0 -1  0  0  0  0]:',
  [array([-1, -1,  0,  1, -1, -1, -1, -1]),
   array([-1, -1,  0,  1, -1, -1, -1,  0]),
   array([-1, -1,  0,  1, -1, -1,  0,  0]),
   array([-1, -1,  0,  1, -1,  0,  0,  0]),
   array([-1, -1,  0,  1,  0,  0,  0,  0])]],
 ['These are for [ 1  1  0 -1  0  0  0  0]:',
  [array([-1, -1,  0,  1, -1, -1, -1, -1]),
   array([-1, -1,  0,  1, -1, -1, -1,  0]),
   array([-1, -1,  0,  1, -1, -1,  0,  0]),
   array([-1, -1,  0,  1, -1,  0,  0,  0])]],
 ['These are for [ 1  1  0 -1  1  0  0  0]:',
  [array([-1, -1,  0,  1, -1, -1, -1, -1]),
   array([-1, -1,  0,  1, -1, -1, -1,  0]),
   array([-1, -1,  0,  1, -1, -1,  0,  0])]],
 ['These are for [ 1  1  0 -1  1  1  0  0]

Thus, the proof of Proposition 3.3.7 of "On lens space surgeries from the Poincaré homology sphere" is complete.